apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-world.fullname" . }}-configmap
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: |-
    {{ $value | nindent 4 }}
  {{- end }}
