apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    app: hello-world
    app.kubernetes.io/instance: hello-world
    app.kubernetes.io/name: hello-world

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-world
      app.kubernetes.io/instance: hello-world
      app.kubernetes.io/name: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        app.kubernetes.io/instance: hello-world
        app.kubernetes.io/name: hello-world
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: {{ include "hello-world.fullname" . }}-configmap
