replicaCount: 3

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

configMap:
  enabled: true
  data:
    index.html: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello World</title>
      </head>
      <body>
        <h1>Hello World</h1>
        <p>Welcome to the Hello World web server running on AKS!</p>
      </body>
      </html>
